"""create clientes table

Revision ID: c922333d0b69
Revises: 
Create Date: 2025-05-26 04:10:13.430218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c922333d0b69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.alter_column('clientes', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
