"""Add ON DELETE CASCADE to cliente_id in pedidos

Revision ID: fad97b0eb4e6
Revises: 98b9abe95b6b
Create Date: 2025-05-26 22:43:24.804694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad97b0eb4e6'
down_revision: Union[str, None] = '98b9abe95b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pedidos_cliente_id_fkey'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('pedidos_cliente_id_fkey'), 'pedidos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
